/**
 * where-to-find-gold-api
 * The api where-to-find-gold 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GoldPlacesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * list all available gold-places
     * 
     * @param latitude latitude for search gold-places
     * @param longitude longitude for search gold-places
     * @param radius radius for search gold-places
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public goldPlacesLatitudeLongitudeRadiusGet(latitude: number, longitude: number, radius: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public goldPlacesLatitudeLongitudeRadiusGet(latitude: number, longitude: number, radius: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public goldPlacesLatitudeLongitudeRadiusGet(latitude: number, longitude: number, radius: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public goldPlacesLatitudeLongitudeRadiusGet(latitude: number, longitude: number, radius: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (latitude === null || latitude === undefined) {
            throw new Error('Required parameter latitude was null or undefined when calling goldPlacesLatitudeLongitudeRadiusGet.');
        }

        if (longitude === null || longitude === undefined) {
            throw new Error('Required parameter longitude was null or undefined when calling goldPlacesLatitudeLongitudeRadiusGet.');
        }

        if (radius === null || radius === undefined) {
            throw new Error('Required parameter radius was null or undefined when calling goldPlacesLatitudeLongitudeRadiusGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/gold-places/${encodeURIComponent(String(latitude))}/${encodeURIComponent(String(longitude))}/${encodeURIComponent(String(radius))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
